### hexo-theme-stellaris

######## head ########
head:
  open_graph:
    enabled: true
  twitter_id: taranakineko


sidebar:
  logo:
    avatar: '[https://nekoq.eu.org/static/images/avatar.png](/about)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[最新](/)'
    archive: '[文章](/archives)'
    links: '[友链](/links)'
    homepage: '[Homepage](https://nekoq.top)'
    #about: # '[关于](/about/)'

  widgets:
    #### 自动生成的页面 ####
    # 主页
    home: search_blog, recent, tagcloud # for home
    # 博客索引页
    blog_index: search_blog, recent # for categories/tags/archives
    # 其它（404）
    others: search, welcome, recent # for 404 and ...
    #### 手动创建的页面 ####
    # 文章内页
    post: toc, ghrepo, search, ghissues # for pages using 'layout:post'
    # 其它 layout:page 的页面
    page: welcome, toc, search # for custom pages using 'layout:page'



######## Main ########
breadcrumb:
  home: home # config.title / config.author / home or custom content


######## Article ########
article:
  outdated_check:
    enabled: true
    month: 24
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 150
  # 分类颜色
  category_color:
    '记录': '#d8d2bb'
    '杂谈': '#5776b9'
    '建站': '#0e83cd'
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 3
    auto_cover: false


######## Comments ########
comments:
  service: waline
  waline:
    js: https://fastly.jsdelivr.net/npm/@waline/client@2.15.8/dist/waline.min.js
    css: https://fastly.jsdelivr.net/npm/@waline/client@2.15.8/dist/waline.min.css
    # Waline server address url, you should set this to your own link
    serverURL: https://waline.nekoq.top/ # waline 地址
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false
    login: disable
    imageUploader: false
    search: false

    # Custom locales
    locale:
      placeholder: '言って。' # 输入框内提示文字

    # Custom emoji
    emoji: 
      - https://fastly.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs


######## Footer ########
footer:
  social:
     - icon: '<img src="/images/mastodon.svg"/>'
       url: 'https://alive.bar/@TaranakiNeko'
     - icon: '<img src="/images/telegram.svg"/>'
       url: 'https://t.me/taranaki_neko'
     - icon: '<img src="/images/github.svg"/>'
       url: 'https://github.com/taranakineko'
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
  source: '[GitHub](https://github.com/taranakineko/blog)'


######## Tag Plugins ########
tag_plugins:
  # {% note text %}
  note:
    default_color: '' # light, dark, red, orange, yellow, green, cyan, blue, purple
  # {% checkbox %}
  checkbox:
    interactive: true # enable interactive for user
  emoji:
    default: /cdn/emoji/qq/%s.gif
    twemoji: https://twemoji.maxcdn.com/%s.svg
    qq: /cdn/emoji/qq/%s.gif
    tieba: /cdn/emoji/tieba/%s.png
  # {% image %}
  image:
    fancybox: true

######## JS Plugins ########
plugins:
  prefetch_and_preconnect: [ "https://fastly.jsdelivr.net", "https://cdn.bootcdn.net", "https://umami.nekoq.eu.org" ]
  ## required plugins ##
  # jquery
  jquery: https://fastly.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js

  ## lazyload plugins ##
  # fancybox
  fancybox:
    enable: true
    js: /js/fancybox.umd.js
    css: /css/fancybox.css
    #selector: .swiper-slide img,.vcontent img:not(.vemoji),article.content :not(div.article-footer) img # 多个选择器用英文逗号隔开
    selector: .swiper-slide img, .vcontent img:not(.vemoji) # 多个选择器用英文逗号隔开
  # swiper
  swiper:
    enable: true
    css: https://cdn.bootcdn.net/ajax/libs/Swiper/6.8.4/swiper-bundle.min.css
    js: https://cdn.bootcdn.net/ajax/libs/Swiper/6.8.4/swiper-bundle.min.js

  # issues api
  sitesjs: /js/plugins/sites.js
  friendsjs: /js/plugins/friends.js

  ## optional plugins ##
  # preload
  instant_click:
    js: /js/instantclick.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://fastly.jsdelivr.net/npm/vanilla-lazyload@17.8.5/dist/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: true
    js: https://fastly.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 20px
    duration: 350 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

style:
  darkmode: auto # auto / always / false
  color:
    common:
      accent: '#ff5722' # 强调色
      button: '#0078d4' # 按钮颜色
      hover: '#0078d4' # 按钮高亮颜色
    light:
      theme: '#4cc2ff' # 主体颜色
      background: '#f3f3f3 radial-gradient(#eff4f9 75%, #f3f3f3 100%) no-repeat fixed' # 网页背景颜色
      mix: '#eff4f9' # 浅色背景颜色
      block: '#EEF0F2' # 块背景颜色
      card: '#fafbfd' # 卡片背景颜色
      title: '#000' # 标题文本颜色
      text: '#1a1a1a' # 正文文本颜色
      code: 'black' # 行内代码颜色
    dark:
      theme: '#4cc2ff' # 主体颜色
      mix: '#313438' #'#313438' # 深色背景颜色
      background: '#202020 radial-gradient(#1a1f35 25%, #202020 100%) no-repeat fixed' # 网页背景颜色
      card: '#282a39' # 卡片背景颜色
      block: '#2B2F33' # 块背景颜色
      title: '#fff' # 标题文本颜色
      text: '#eee' # 正文文本颜色
      code: '#eee' # 行内代码颜色
      background-mobile: black # 移动端深色背景（OLED调成纯黑可以省电）
  animated_avatar:
    animate: auto # auto, always
    background: https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.4/avatar/round/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px
    highlightjs_theme: https://cdn.bootcdn.net/ajax/libs/highlight.js/11.6.0/styles/atom-one-light.min.css
  font-family:
    logo: "'Inter var', HarmonyOS_Regular, system-ui, -apple-system, sans-serif"
    body: "'Inter var', 'Noto Color Emoji', HarmonyOS_Regular, system-ui, -apple-system, sans-serif"
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  custom_font_css:
    # 自定义字体
    enabled: true
    css: "https://s1.hdslb.com/bfs/static/jinkela/long/font/regular.css"

default:
  avatar: /images/avatar.svg
  link: /images/link.svg
  cover: /images/cover.svg
  image: /images/image.svg

search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)


api_host:
  ghapi: https://r.ydz1.gq/https://api.github.com
  ghraw: https://www.githubs.cn/raw-githubusercontent
  gist: https://r.ydz1.gq/https://gist.github.com

######## 自定义插件 ########
inject:
  head:
    - '<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#202020"></meta>'
    - '<link rel="stylesheet" href="/css/inter.css">'
    - '<link rel="me" href="https://alive.bar/@TaranakiNeko">'
  script:
    - '<script async defer data-website-id="80e637e6-9cdd-4675-a19d-519785bdb3a8" src="https://umami.nekoq.eu.org/nya" data-do-not-track="true" data-domains="taranakineko.pages.dev,nekoq.eu.org,blog.nekoq.top"></script>'
  # script:
  #   # 使用 HTML 语法
  #   - '<script src="https://example.com/my_script.js" data-no-instant="true"></script>'
  #   # data-no-instant 为 InstantClick 属性，决定某脚本在页面切换时是否重新加载
  #   # 如果此脚本只需要加载一次（比如添加全局对象），那么为 true
  #   # 如果此脚本每页都需要重复加载（比如编辑页面元素或需要使用 window.onload），那么为 false
  # head:
  #   # 使用 HTML 语法
  #   - '<meta name="key" content="value"></meta>'
  #   - '<link rel="stylesheet" href="/css/1.css"></link>'
  # 由于 Stylus 的特性，暂不支持 inject CSS
  # 如果要使用自定义 CSS，请在 _source/css 下创建 css 文件
  # 之后使用上文的 head 来引入
